### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by stoically** [nazar-pc/ronion#1]
Hi,

it's nice to see someone working on a generic approach to onion-routing! I was planning to implement something similar in an App and would like to use your lib for it.

Could you maybe put together a minimal, opinionated usage example that actually uses a transport-layer and encryption? I feel like that could greatly help adoption in general. It might also serve as additional integration test? I did look at the existing test, but had a hard time to understand it - that's why I'm asking.

Thanks for your work and best regards

**Comment by nazar-pc** [comment]
Tests are difficult to read, but you primarily need just look at events handlers: https://github.com/nazar-pc/ronion/blob/master/tests/index.ls#L83-L133

There is an opinionated (though, not minimal) use in [Detox](https://github.com/Detox) project I'm working on (this library albeit standalone was created with plans to use there).
You can take a look at `Router` object here: https://github.com/Detox/detox-transport/blob/master/src/index.ls
It uses Ronion for its routing purposes and includes encryption among other things. In fact, if you like API and encryption algorithms, you can also use `detox-transport` as standalone library directly. It is also covered by tests.

Yet another library on top of that is `detox-core`, which uses `DHT` and `Router` from `detox-transport` and provides extremely simple end-user API, but you probably don't need to go that far.

**Comment by stoically** [comment]
Thanks for the fast response. Detox project looks great!

detox-transport poses the same problem for me tho, I can't get my head around how to actually use a transportation layer with it. Also it seems that the transport package is hard-wired to your DHT implementation - and I'm already using something else for that.

My understanding of the onion protocol is really limited but I would expect an API around these lines:

Every Node listens for packets and is able to forward them:
```js
const ronion = new ROnion();
ronion.setDecryptionMethod(myDecryptionMethod);

const handleIncomingOnion = () => {
  const onionPacket = ronion.process_packet(data);
  if (onionPacket.payload) {
    // we're the last node in the path, do something with the payload
    return;
  }

  if (onionPacket.forward) {
    // we're not the last node in the path, forward it
    const client = net.createConnection({
      host: onionPacket.forward.address.host,
      port: onionPacket.forward.address.port
    }, () => {
      client.write(onionPacket);
    });
  }
}

const net = require('net');
const server = net.createServer((c) => {
  c.on('data', async (data) => {
    handleIncomingOnion(data);
  });
});

server.listen(8124);
```

The initiator node creates the onion and sends it on its way:
```js
const payloadData = {actual: 'payload'};
const nodePath = [
  {address: {host: '127.0.0.1', port: 8124}, publicKey: '..'},
  {address: {host: '127.0.0.2', port: 8124}, publicKey: '..'},
  {address: {host: '127.0.0.3', port: 8124}, publicKey: '..'}
];

const ronion = new ROnion();
ronion.setEncryptionMethod(myEncryptionMethod);
const onionPacket = ronion.createOnion(payloadData);
onionPacket.addLayer(nodePath[2]);
onionPacket.addLayer(nodePath[1]);
onionPacket.addLayer(nodePath[0]);

const net = require('net');
const client = net.createConnection({
  host: nodePath[0].address.host,
  port: nodePath[0].address.port
}, () => {
  client.write(onionPacket);
});
```

I'm sure this is already possible with ronion, so could you maybe help me fill out the missing parts and make it actually work? That would be great! And sorry if I seem ignorant regarding your API and/or spec, it's just that I can't wrap my head around it.

Thanks again.

**Comment by nazar-pc** [comment]
> Also it seems that the transport package is hard-wired to your DHT implementation - and I'm already using something else for that

By dependencies - yes, however, DHT and Router objects are independent and even their tests are in separate files. Only `detox-core` combines them together.

Now about your snippets: `handleIncomingOnion` logic is already included within Ronion itself. You just feed into it a packet you've received from another node and it'll handle it. Similarly if Ronion fires `send` event - you just blindly send it where it wants.

`setDecryptionMethod` is replaced with `encrypt` and `decrypt` events - you add event handlers and handle them accordingly:
https://github.com/nazar-pc/ronion/blob/d4d38882d9018b640dad5b07ac8b4133414a4aa9/tests/index.ls#L112-L121

Note that `address` and `segment_id` represent routing path, `target_address` is specific node on that routing path and `plaintext`/`ciphertext` is what you need to encrypt/decrypt. You need to prepare encryption keys during creation of routing path segment by sending necessary bits as payload. For instance, here `get_handshake_message` is called and its output is sent to the other side:
https://github.com/Detox/detox-transport/blob/cef4cb38cb339e472c56df266d4ea700904d8639/src/index.ls#L682-L684
And the other side handles it accordingly:
https://github.com/Detox/detox-transport/blob/cef4cb38cb339e472c56df266d4ea700904d8639/src/index.ls#L479-L485

`createOnion` is replaced with `create_request`:
https://github.com/nazar-pc/ronion/blob/d4d38882d9018b640dad5b07ac8b4133414a4aa9/tests/index.ls#L230-L232

It'll fire corresponding event on the target node:
https://github.com/nazar-pc/ronion/blob/d4d38882d9018b640dad5b07ac8b4133414a4aa9/tests/index.ls#L83-L92

If everything is fine - call `confirm_incoming_segment_established()`.

Once you get response on your `create_request`, you'll get `create_response` event:
https://github.com/nazar-pc/ronion/blob/d4d38882d9018b640dad5b07ac8b4133414a4aa9/tests/index.ls#L93-L98

If everything is fine - call `confirm_outgoing_segment_established()`.

Once you've created routing path, you can extend it (similar to your `addLayer`) with `extend_request`:
https://github.com/nazar-pc/ronion/blob/d4d38882d9018b640dad5b07ac8b4133414a4aa9/tests/index.ls#L225-L228

And you'll get `extend_response` back:
https://github.com/nazar-pc/ronion/blob/d4d38882d9018b640dad5b07ac8b4133414a4aa9/tests/index.ls#L99-L106

If everything is fine - call `confirm_extended_path()` and extend it further if needed.

I'd encourage you to read the design document: https://github.com/nazar-pc/ronion/blob/master/design.md#packets-forwarding-diagrams
And ideally the spec, as methods and events are named as in the spec.

**Comment by stoically** [comment]
I really [tried](https://gist.github.com/stoically/1505dcf7fb77036447deda52acafbbb4) to implement it using only ronion (based on the test), but I had a hard time figuring out where to send which keys. So I checked detox-transport again and it turned out that it's easier than I first thought. I came up with [this solution](https://gist.github.com/stoically/48de43a5f5de0f770ea5c624797b17b0) based on the Router test - it was only a matter of bridging the `send` event.

Thanks for taking the time to explain it in detail!

**Comment by nazar-pc** [comment]
Glad to know that you've got something working.

I'll try to address your question about keys. The goal is to establish 2 pairs of keys on 2 sides talking to each other so that messages can be independently encrypted in one direction or another and decrypted when received.

You can use plain Diffie-Hellman key exchange here, in which case you'll exchange g^a and g^b as payload on `create_request()`/`extend_request()` and `create_response()` methods calls accordingly. You'll need to have such pairs of encryption keys between initiator that constructs routing path and each node on it including responder, so that you can encrypt message for specific node on routing path and that specific node can send encrypted messages back to you.

Test case here does a brutal hack by storing keys on instances objects directly, since they are all within the same process. It works for tests, but not suitable for anything remotely related to production.

`detox-transport` uses [Noise](https://noiseprotocol.org/noise.html) and thus instead of g^a and g^b it sends Noise handshakes. Noise also provides forward secrecy and some other benefits just to make sure you do not make horribly wrong decisions in terms of crypto.

Let me know if there are any other questions. This project is relatively new and I'd like to make sure it is generic and useful enough for other people.
